#!/usr/bin/env node
/**
 * Renders boxes/<alias>/ from configs/codebox.yml:
 *
 *   Dockerfile          one toolchain stage per configured language + the
 *                       telemetry runners, setup and metrics scripts
 *   docker-compose.yml  service `box`, container codebox-<alias>
 *   config.yml          the resolved box config (read by the MCP server)
 *   .env                box env vars
 *   codes/              init codes (existing files are kept unless --force)
 *   logs/ runs/         monitoramento.log, top_snapshot.log, per-run output
 *   .codebox/runtime/   build context copy of codebox/runtime
 *
 * Usage: node tools/codebox/render.mjs <alias> [--config file] [--runtime runsc|runc] [--force]
 * Prints a JSON summary on stdout.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';
import { CodeboxConfigError, REPO_ROOT, boxesRoot, loadCodeboxConfig, resolveBox } from './lib/boxes.mjs';

const RUNTIME_SRC = path.join(REPO_ROOT, 'tools', 'codebox', 'runtime');
const RUNTIME_SKIP = new Set(['node_modules', 'target', 'dist', '.zig-cache', 'zig-out', '__pycache__']);
const PROXY_VARS = ['HTTP_PROXY', 'HTTPS_PROXY', 'NO_PROXY', 'http_proxy', 'https_proxy', 'no_proxy'];
const CA_ENV = [
  'SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt',
  'REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt',
  'PIP_CERT=/etc/ssl/certs/ca-certificates.crt',
  'CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt',
  'GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt',
  'NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/codebox-extra.crt',
];

export function renderDockerfile(box, { hasCaCert = false } = {}) {
  const has = (lang) => box.languages.includes(lang);
  const { images } = box;
  const lines = [
    '# syntax=docker/dockerfile:1',
    `# Generated by \`./codebox up ${box.alias}\` from configs/codebox.yml — edit the config, not this file.`,
    `# Languages: ${box.languages.join(', ')}`,
  ];
  if (has('typescript')) lines.push(`FROM ${images.node} AS node`);
  if (has('python')) lines.push(`FROM ${images.python} AS python`);
  if (has('go')) lines.push(`FROM ${images.go} AS go`);
  if (has('rust')) lines.push(`FROM ${images.rust} AS rust`);

  lines.push(
    '',
    `FROM ${images.base}`,
    `ENV CODEBOX_HOME=/opt/codebox \\`,
    `    CODEBOX_BOX=${box.alias} \\`,
    `    PATH=/opt/codebox/bin:$PATH`,
  );
  if (hasCaCert) {
    lines.push(
      '',
      '# extra CA (corporate proxy)',
      'COPY .codebox/ca.crt /usr/local/share/ca-certificates/codebox-extra.crt',
      'RUN update-ca-certificates',
      `ENV ${CA_ENV.join(' \\\n    ')}`,
    );
  }
  if (has('typescript')) {
    lines.push(
      '',
      '# --- typescript / node',
      'COPY --from=node /usr/local/bin/node /usr/local/bin/node',
      'COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules',
      'RUN ln -sf ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \\',
      ' && ln -sf ../lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx \\',
      ' && node --version && npm --version',
    );
  }
  if (has('python')) {
    lines.push(
      '',
      '# --- python (one venv shared by the runner, setup and user code)',
      'COPY --from=python /usr/local/ /usr/local/',
      'RUN ldconfig && python3 -m venv /opt/codebox/venv',
      'ENV VIRTUAL_ENV=/opt/codebox/venv PATH=/opt/codebox/venv/bin:$PATH',
    );
  }
  if (has('go')) {
    lines.push(
      '',
      '# --- go',
      'COPY --from=go /usr/local/go /usr/local/go',
      'ENV GOPATH=/root/go GOTOOLCHAIN=local PATH=/usr/local/go/bin:/root/go/bin:$PATH',
      'RUN go version',
    );
  }
  if (has('rust')) {
    lines.push(
      '',
      '# --- rust',
      'COPY --from=rust /usr/local/cargo /usr/local/cargo',
      'COPY --from=rust /usr/local/rustup /usr/local/rustup',
      'ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo PATH=/usr/local/cargo/bin:$PATH',
      'RUN (rustup component add rustfmt || echo "rustfmt unavailable: setup skips the rust syntax preflight") && rustc --version',
    );
  }
  if (has('zig')) {
    lines.push(
      '',
      '# --- zig (ziglang.org tarball, PyPI "ziglang" wheel as fallback)',
      `ARG ZIG_VERSION=${box.zig_version}`,
      'RUN set -eu; arch="$(uname -m)"; mkdir -p /opt/zig; \\',
      '    if curl -fsSL "https://ziglang.org/download/${ZIG_VERSION}/zig-${arch}-linux-${ZIG_VERSION}.tar.xz" -o /tmp/zig.tar.xz; then \\',
      '      tar -xJf /tmp/zig.tar.xz -C /opt/zig --strip-components=1; rm -f /tmp/zig.tar.xz; \\',
      '    else \\',
      '      url="$(curl -fsSL "https://pypi.org/pypi/ziglang/${ZIG_VERSION}/json" | grep -o "https://[^\\"]*manylinux[^\\"]*${arch}[^\\"]*\\.whl" | head -n 1)"; \\',
      '      curl -fsSL "$url" -o /tmp/zig.whl; unzip -q /tmp/zig.whl "ziglang/*" -d /tmp/zigwhl; \\',
      '      cp -a /tmp/zigwhl/ziglang/. /opt/zig/; chmod +x /opt/zig/zig; rm -rf /tmp/zig.whl /tmp/zigwhl; \\',
      '    fi; /opt/zig/zig version',
      'ENV PATH=/opt/zig:$PATH',
    );
  }

  lines.push('', '# --- codebox runtime: setup, codebox-run, codebox-metrics + telemetry runners', 'COPY .codebox/runtime /opt/codebox', 'RUN chmod +x /opt/codebox/bin/*');
  if (has('typescript')) {
    lines.push(
      'RUN cd /opt/codebox/runners/ts && npm install --no-audit --no-fund \\',
      ' && ./node_modules/.bin/tsc -p tsconfig.json',
    );
  }
  if (has('python')) lines.push('RUN pip install --no-cache-dir -r /opt/codebox/runners/py/requirements.txt');
  if (has('go')) {
    lines.push('RUN cd /opt/codebox/runners/go && go build -trimpath -o /usr/local/bin/codebox-run-go . && go clean -cache');
  }
  if (has('rust')) {
    lines.push(
      'RUN cd /opt/codebox/runners/rs && cargo build --release \\',
      ' && cp target/release/codebox-run-rs /usr/local/bin/ && rm -rf target',
    );
  }
  if (has('zig')) {
    lines.push(
      'RUN cd /opt/codebox/runners/zig \\',
      ' && zig build-exe telemetry.zig -O ReleaseSafe --cache-dir /tmp/zig-cache -femit-bin=/usr/local/bin/codebox-run-zig \\',
      ' && rm -rf /tmp/zig-cache /usr/local/bin/codebox-run-zig.o',
    );
  }
  lines.push('', 'WORKDIR /workspace/codes', 'CMD ["sleep", "infinity"]', '');
  return lines.join('\n');
}

export function renderCompose(box, { runtime }) {
  const service = {
    build: { context: '.', dockerfile: 'Dockerfile' },
    image: `codebox/${box.alias}:latest`,
    container_name: box.container,
    env_file: ['.env'],
    working_dir: '/workspace/codes',
    command: ['sleep', 'infinity'],
    init: true,
    restart: 'unless-stopped',
    volumes: ['./codes:/workspace/codes', './logs:/workspace/logs', './runs:/workspace/runs'],
    security_opt: ['no-new-privileges:true'],
  };
  if (box.build_network) service.build.network = box.build_network;
  if (box.proxy === 'inherit') {
    service.build.args = Object.fromEntries(PROXY_VARS.map((name) => [name, `\${${name}:-}`]));
  }
  if (runtime === 'runsc') service.runtime = 'runsc';
  if (box.network && box.network !== 'bridge') service.network_mode = box.network;
  if (box.resources?.cpus) service.cpus = String(box.resources.cpus);
  if (box.resources?.memory) service.mem_limit = String(box.resources.memory);
  if (box.resources?.pids) service.pids_limit = Number(box.resources.pids);
  return [
    `# Generated by \`./codebox up ${box.alias}\` from configs/codebox.yml — edit the config, not this file.`,
    YAML.stringify({ name: box.container, services: { box: service } }),
  ].join('\n');
}

export function renderEnv(box) {
  const vars = {
    COMPOSE_PROJECT_NAME: box.container,
    CODEBOX_BOX: box.alias,
    CODEBOX_LANGUAGES: box.languages.join(','),
    CODEBOX_TIMEOUT_MS: String(box.timeout_ms),
    OTEL_SERVICE_NAME: box.container,
    ...box.env,
  };
  if (box.proxy === 'inherit') {
    for (const name of PROXY_VARS) if (process.env[name]) vars[name] = process.env[name];
  }
  const quote = (v) => (/^[\w@%+=:,./-]*$/.test(v) ? v : JSON.stringify(v));
  return `${Object.entries(vars).map(([k, v]) => `${k}=${quote(v)}`).join('\n')}\n`;
}

function displayPath(file) {
  const rel = path.relative(REPO_ROOT, file);
  return rel.startsWith('..') ? file : rel;
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (RUNTIME_SKIP.has(entry.name) || entry.name.endsWith('.lock') || entry.name === 'package-lock.json') continue;
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

export function renderBox(alias, { configPath, root, runtime = 'runc', force = false } = {}) {
  const config = loadCodeboxConfig(configPath);
  const box = resolveBox(config, alias);
  const dir = path.join(boxesRoot(root), alias);
  const resolvedRuntime = box.runtime === 'auto' ? runtime : box.runtime;

  for (const sub of ['codes', 'logs', 'runs', '.codebox']) fs.mkdirSync(path.join(dir, sub), { recursive: true });

  const runtimeDest = path.join(dir, '.codebox', 'runtime');
  fs.rmSync(runtimeDest, { recursive: true, force: true });
  copyDir(RUNTIME_SRC, runtimeDest);

  const caDest = path.join(dir, '.codebox', 'ca.crt');
  fs.rmSync(caDest, { force: true });
  if (box.ca_cert) {
    if (!fs.existsSync(box.ca_cert)) throw new CodeboxConfigError(`ca_cert not found: ${box.ca_cert}`);
    fs.copyFileSync(box.ca_cert, caDest);
  }

  fs.writeFileSync(path.join(dir, 'Dockerfile'), renderDockerfile(box, { hasCaCert: Boolean(box.ca_cert) }));
  fs.writeFileSync(path.join(dir, 'docker-compose.yml'), renderCompose(box, { runtime: resolvedRuntime }));
  fs.writeFileSync(path.join(dir, '.env'), renderEnv(box));
  const { init, ...resolved } = box;
  fs.writeFileSync(
    path.join(dir, 'config.yml'),
    `# Resolved config of box "${alias}" (generated from ${displayPath(config.path)}).\n${YAML.stringify({
      ...resolved,
      runtime: resolvedRuntime,
      init: init.map((item) => item.path),
      rendered_at: new Date().toISOString(),
    })}`,
  );

  const written = [];
  const kept = [];
  for (const item of init) {
    const target = path.join(dir, 'codes', item.path);
    if (fs.existsSync(target) && !force) {
      kept.push(item.path);
      continue;
    }
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, item.content);
    written.push(item.path);
  }
  return { alias, dir, container: box.container, languages: box.languages, runtime: resolvedRuntime, init: { written, kept } };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const opt = (name) => {
    const i = args.indexOf(name);
    return i >= 0 ? args.splice(i, 2)[1] : undefined;
  };
  const configPath = opt('--config');
  const runtime = opt('--runtime');
  const root = opt('--root');
  const force = args.includes('--force');
  const alias = args.find((a) => !a.startsWith('--'));
  if (!alias) {
    process.stderr.write('usage: render.mjs <alias> [--config file] [--root dir] [--runtime runsc|runc] [--force]\n');
    process.exit(64);
  }
  try {
    process.stdout.write(`${JSON.stringify(renderBox(alias, { configPath, root, runtime, force }))}\n`);
  } catch (err) {
    process.stderr.write(`codebox: ${err.message}\n`);
    process.exit(err instanceof CodeboxConfigError ? 65 : 1);
  }
}
